### PR TITLE
zrtp: Removed wrong minus signs in front of error return codes

### PR DESCRIPTION
**Pull request by db-tech**
#36 Because of refactoring there where some leftover minus signs

### CODE REVIEW

**Comment by polusto** [comment]
Thanks for the PR.

Although I don't have a good idea what is supposed to got to the beginning of a commit, to me it feels "zrtp:" is better than "common:". Maybe @altonen can shed some light on his naming conventions regarding commits. 

Those naming conventions should definitely be defined somewhere and I struggle with them as well. Especially, the use of "common:".

**Comment by altonen** [comment]
Thanks for fixing this.

I listed some subsystems in docs/subsystems and going by the values listed there, this should be crypto but it's not very fitting. I think zrtp would be a better prefix for the commit than common. I didn't think the list all the way through but my line of thinking was that if a commit touched multiple files, or if the area it modified was not clearly defined (e.g., some function in media_stream.cc), it could use the common prefix.

Maybe you or Marko could define subsystems for your liking, especially if this common is too vague in your opinion.

**Comment by db-tech** [comment]
I am not sure what would be a good prefix, I usually don't use any besides issue number and/or type.
It might depend
I can certainly replace it with zrtp
The only important thing in my opinion would be that it is well documented and easy to do so there is no hurdle for people to contribute.
Usually a "How to contribute" part in the documentation is helpful in this regard.

**Comment by polusto** [comment]
I took the time and wrote instruction on how to contribute and added a link to readme. That is just my view and maybe @altonen has something to comment.

**Pull request merged**
