### PR TITLE
[UVG-89] Fix miscalculation of data length in T3 and T4 scenario

### PR DESCRIPTION
**Pull request by jhkimura**
Corrects the issue in the T3 & T4 scenario listed under issue [#89](https://github.com/ultravideo/uvgRTP/issues/89).

This is due to the difference between the h264 start position and the length of the start code.

While this solution is less than ideal in terms of code quality.  I currently do not have the time to factor the code and want to make as little change as possible.

Verified the following:
Built in Linux
Verified the output of the RTP packets by dumping the packets to a file and comparing with the original H264 frames.  I was able to verify that the bytes that were lost in these scenarios were recovered by a before and after.

### CODE REVIEW

**Comment by jrsnen** [comment]
Hi and thanks for this PR! Sorry I took so long to review this pull request. I tested this on Windows and encountered no problems. 

I have one request that you add text `formats: ` to the beginning of the commit message, since that is the current style of this repository. Amending and force pushing the branch is the easiest way to do this.

- Joni

**Comment by jhkimura** [comment]
I've amended my commit message as requested above.  Not sure if thats what you were looking for.  Can also squash and merge with the appropriate commit message.

**Comment by jrsnen** [comment]
I should have been more specific, the point was mainly to avoid additional commit messages using git `--amend` parameter. Please make it so that there is only one commit in the branch.

**Comment by jhkimura** [comment]
Thats exactly what I did to amend my commit.  I don’t think it has the effect you are looking for. Regardless, you can squash and merge the commit to get whatever commit message you are looking for.

**Comment by jrsnen** [comment]
I'm sorry, but I cannot modify pull requests.

**Comment by jhkimura** [comment]
Amending a git commit seems to add another commit line because I’m making a PR from my fork as I don't have direct access to your repo.  I will close the PR. Feel free to create the PR as these fixes were only to help your community and I have resolved the issue in my personal project.

**Comment by jrsnen** [comment]
I managed to cherry-pick the commits. Thanks for your help!

**Pull request closed without merging**
