### PR TITLE
Issue#14 pull request

### PR DESCRIPTION
**Pull request by lhp-git**
I am using the uvgRTP 1.0.0 on a multimedia CentOS7 project. I would like to upgrade to the 2.0.0 version but it doesn't compile anymore, and the OS upgrade is not an option.

This pull request allows the compilation of uvgRTP on CentOS7 where c++17 and the getrandom() functions aren't available.

The CMakeLists.txt checks the c++ compiler standard conformance and adjusts the compilation directive -std accordingly.
It checks also the availability of the getrandom() function and creates the HAVE_GETRANDOM preprocessor definition if this function exists.

If the getrrandom() function doesn't exist, the equivalent syscall replaces it.

If the c++ compiler is a c++17 or higher one, and the getrandom() is available, the original code is left unchanged

### CODE REVIEW

**Comment by polusto** [comment]
Hello and thank you for your pull request.

I'm not very familiar with cmake compilation, but I can give couple of comments at this point for this pull request:
- Commit message should follow the same format as other commit messages. Something like ```build: Build support for non-c++17 compilers``` Followed by a short description of the changes made. Here you may also mention the issue number.
- The cmake c++ version check does not work for visual studio (MSVC). From [here](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html) I read that just setting the CXX_STANDARD should be enough since it automatically decays to older standard if the newer is not supported. Like this: ```set(CXX_STANDARD 17)```. 
- The HAVE_GETRANDOM check fails on MSVC. Not sure if it is supposed to succeed.

I will test actual compilation once the cmake succeeds.

**Comment by lhp-git** [comment]
Hi,
I tested my pull request on CentOS7.9, where gcc/g++ supports only c++11 and the getrandom() function doesn't exists in glibc. I tested it also on CentOS 8 Stream, where gcc/g++ supports c++17, and the glibc library has the getrandom() function.
Both builds were sucessfull.

I don't develop under Windows, and I don't have a MSVC compiler.
The cmake version check shall know if c++11 or c++17 is supported, because we must pass the corresponding parameter to gcc (-std=c++11 or -std=c++17). Using only CXX_STANDARD cannot do that.

Could you test the build on a Linux machine ?
I don't know if I can change my commit message. This is my first pull request since several years.
I will do better next time.

**Comment by altonen** [comment]
I would also like to see the commit message getting fixed. You just need to `git commit --amend`, modify the message according to Joni's comments and `git push --force`.

`HAVE_GETRANDOM` is not suppose to work (at least in its current condition) on Windows and I guess it doesn't have to either but the CMake file should still produce valid build files for all supported platforms.

**Comment by polusto** [comment]
I can do the MSVC testing, but you have to make changes to pull request so also MSVC works.

The issue with CXX_STANDARD is probably in the cmake file. According to the link I posted, it should work, but there may be some lines preventing it from working. I tried fixing it, but the result was, that debug prints got enabled and that is probably not desirable.

**Comment by polusto** [comment]
I updated the cmake file. Cmake should now use the correct compiler flag(even if 17 is missing) if I understood things correctly. Can you test the new cmake file with your changes and modify this pull request (by excluding the cmakelists.txt modifications)?

**Comment by lhp-git** [comment]
I will test it on Thursday, and modify my commit message. Sorry, I have no time available before.

**Comment by lhp-git** [comment]
Hi,
I tested the polusto changes on CentOS7 (c++11 g++ compiler, no getrandom()) and CentOS8 stream (c++17 g++ compiler and getrandom()) : it doesn't compile anymore. The -std=c++11 or -std=c++17 aren't added to the compile options in spite of the set(CMAKE_CXX_STANDARD 17) directive.

I had to revert, for UNIX target, the computation of the compiler definitions and options to the one of my original pull request.

Therefore, the uvgrtp library compiles successfully on CentOS7 and CentOS8

**Comment by polusto** [comment]
I didn't do anything for the getrandom. You still need those changes in CMakeLists. I just tried to set the compiler version as described by cmake in documentation.

What exactly was the problem? How did you verify the compiler option were not present? It seems that that cmake compiles a separate program for determining those flags. I tried to make the changes easier by handling the flag setting automatically. If you are convinced this does not work, you can also try to check for the correct flags on windows in your solution (something like --std=/17 seems to be in use looking at previous solutions). I can accept anything that works on all platforms and improve it later.

As you may guess, we cannot accept this a branch with multiple merge commits and multiple commit headers with same name. You should start your process with the master branch and build your commits on top of that. The end results should have one, at most two commits (preferably one) that compile.

**Comment by polusto** [comment]
I did some testing and you were right, the flag were not set correctly. I did another commit that should fix the issues. I also checked the CXX_FLAGS on linux and the flag is now there.

image

**Comment by lhp-git** [comment]
To get a chance that my pull request get accepted, I close this one and will open a fresh new one. I will do my best to follow your pull request acceptance criteria.

**Comment by polusto** [comment]
Technically you could just force push the branch (as Aaro mentioned) and this pull request would have updated automatically. How I understand it is that a pull request is basically just a reference to a branch in another repo. Creating a new pull request works too.

**Pull request closed without merging**
