### PR TITLE
rtcp: add a public getter function for interval_ms_

### PR DESCRIPTION
**Pull request by wowaser**
Currently there is no way of knowing what the interval is

### CODE REVIEW

**Comment by jrsnen** [comment]
Hi. If you can 1) add ms to end of function for clarity, 2) change return type to something like uint32_t since int doesn't make sense (the internal type doesn't make sense either, but it can be more easily changed) and 3) add const qualifier to the function, that would be nice.

Suggesting these now, since changing APIs later is something we try to avoid.

**Comment by jrsnen** [comment]
Would it be possible to merge the commits, so there is only one commit in commit log? Having small commits that fix few lines makes reading the git log harder.

**Comment by jrsnen** [comment]
I guess the git command is squash and the force push to PR branch

**Comment by jrsnen** [comment]
const is still missing

**Comment by jrsnen** [comment]
or rather in wrong place

**Comment by jrsnen** [comment]
uint32_t get_rtcp_interval_ms() const; 

is what I meant

**Comment by wowaser** [comment]
Damn one second

**Comment by jrsnen** [comment]
Ok, this I can merge. Thanks!

**Pull request merged**
